{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zys",
    "module": "globecore",
    "version": "0.1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "globecore-0.1.1.0.aar",
          "url": "globecore-0.1.1.0.aar",
          "size": 17799117,
          "sha512": "8f6752b8dde3f96edf55759231d09eec75fef6c1323d9122acf3613ec16f0f1ea9edbe62d1be8dc7f0ee5f81ef26300b090d99691acb5957ca271adfd770b92c",
          "sha256": "7cefdb74cd5b8de519060877b3c969cc28c0caa1d50c4372c81e76fe2b4af9ec",
          "sha1": "9bdfd0b9901ff2a51a6751a35f56b80ba951df37",
          "md5": "d73f02999d45f0bf228a4284978f1413"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "globecore-0.1.1.0.aar",
          "url": "globecore-0.1.1.0.aar",
          "size": 17799117,
          "sha512": "8f6752b8dde3f96edf55759231d09eec75fef6c1323d9122acf3613ec16f0f1ea9edbe62d1be8dc7f0ee5f81ef26300b090d99691acb5957ca271adfd770b92c",
          "sha256": "7cefdb74cd5b8de519060877b3c969cc28c0caa1d50c4372c81e76fe2b4af9ec",
          "sha1": "9bdfd0b9901ff2a51a6751a35f56b80ba951df37",
          "md5": "d73f02999d45f0bf228a4284978f1413"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "globecore-0.1.1.0-sources.jar",
          "url": "globecore-0.1.1.0-sources.jar",
          "size": 30536,
          "sha512": "9c6a38e7745d5ca6c70c045bb8329eec75679c5b85fe4874253a98aa7f1e9255b32d41c7833b8214b7d3cf0606919d73e86736b2b8986f1419938d2d597765fd",
          "sha256": "68248721ff07335f40624b689146d8375679ad35d56e4413a559fe1bfc1172ca",
          "sha1": "0232052adb295e7b43ae4ab01e64139fee8f7bfa",
          "md5": "2e2dc5895c34a8b4f60769752722d562"
        }
      ]
    }
  ]
}
