{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zys",
    "module": "globecore",
    "version": "0.1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "globecore-0.1.1.0.aar",
          "url": "globecore-0.1.1.0.aar",
          "size": 17799119,
          "sha512": "e30cfadf05ad99e2c59dc12c5eaa8dda3f805881a4887dedeee62abc21071c2c1b7704da3172a92bd46aeb9ffd6515db8830fdbeaf3dc57fa7e9fac449e6b8ae",
          "sha256": "53076567b4a9e33beb93bdaae0d42c05216ec8327b13704fdd64add79a5c9535",
          "sha1": "fee778da9bfe61484324f4bc230692e07c2fa6d1",
          "md5": "8ca0924f9d60f9ea7f490e7a91fcb94f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "globecore-0.1.1.0.aar",
          "url": "globecore-0.1.1.0.aar",
          "size": 17799119,
          "sha512": "e30cfadf05ad99e2c59dc12c5eaa8dda3f805881a4887dedeee62abc21071c2c1b7704da3172a92bd46aeb9ffd6515db8830fdbeaf3dc57fa7e9fac449e6b8ae",
          "sha256": "53076567b4a9e33beb93bdaae0d42c05216ec8327b13704fdd64add79a5c9535",
          "sha1": "fee778da9bfe61484324f4bc230692e07c2fa6d1",
          "md5": "8ca0924f9d60f9ea7f490e7a91fcb94f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "globecore-0.1.1.0-sources.jar",
          "url": "globecore-0.1.1.0-sources.jar",
          "size": 30536,
          "sha512": "9c6a38e7745d5ca6c70c045bb8329eec75679c5b85fe4874253a98aa7f1e9255b32d41c7833b8214b7d3cf0606919d73e86736b2b8986f1419938d2d597765fd",
          "sha256": "68248721ff07335f40624b689146d8375679ad35d56e4413a559fe1bfc1172ca",
          "sha1": "0232052adb295e7b43ae4ab01e64139fee8f7bfa",
          "md5": "2e2dc5895c34a8b4f60769752722d562"
        }
      ]
    }
  ]
}
